all:
	
	g++ main.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_features2d -lopencv_gpu -std=c++11 -o Axis.out 
debug:
	g++ -g main.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_features2d -opencv_gpu -std=c++11 -o Axis_Debug.out

